In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import log_loss, confusion_matrix, f1_score, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.cross_validation import StratifiedKFold
from sklearn.neural_network import MLPClassifier

from utils import *

from sklearn.metrics import log_loss, confusion_matrix, f1_score, accuracy_score

/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df_train = np.load('../cache/train_stage2_fe2.npy')
df_test = np.load('../cache/test_stage2_fe2.npy')
df = pd.read_csv('../cache/stage2_labels.csv')
y = df['y'].values

df = pd.read_csv('../cache/stage2_test_id.csv')
pid = df.ID.values

wts_per_class = np.load('../cache/stage2_train_weights_per_class.npy')
wts_per_class = wts_per_class.tolist()
print(wts_per_class)

{1: 4.572507552870091, 2: 6.407630522088353, 3: 37.427083333333336, 4: 3.912117177097204, 5: 12.816479400749063, 6: 11.42087542087542, 7: 2.5, 8: 174.66666666666666, 9: 84.79069767441861}


In [3]:
y = y-1

In [4]:
wts_per_class2 = {}
wts_per_class2 = {i:wts_per_class[i+1] for i in y}

In [5]:
w = np.array([wts_per_class[j+1] for j in y], )

In [6]:
mlp_model = MLPClassifier()

# MLPClassifier(hidden_layer_sizes=(100, ), activation=’relu’, solver=’adam’, alpha=0.0001, 
#               batch_size=’auto’, learning_rate=’constant’, learning_rate_init=0.001, 
#               power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, 
#               verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
#               early_stopping=False, validation_fraction=0.1,
#               beta_1=0.9, beta_2=0.999, epsilon=1e-08)
parameters = {
    'solver': ['adam', 'sgd'], 
    'max_iter': [50,250,500],
    'learning_rate_init': [0.001, 0.0001, 0.01, 0.1],
    'alpha': [0.001],
    'power_t': [0.1],
    'random_state': [1337],
}

clf = GridSearchCV(mlp_model, parameters, n_jobs=4, 
                   cv=StratifiedKFold(y, 5, True),
                   scoring = 'neg_log_loss',
                   verbose=2, refit=True)



In [7]:
clf.fit(df_train, y)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam 
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam 
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam 
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=   5.8s
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=   9.1s
[CV] alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.001, max_iter=50, power_t=0.1, random_state=1337, sol

[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:  1.0min


[CV]  alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=   5.6s
[CV] alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=   4.7s
[CV] alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.1s
[CV] alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.9s
[CV] alpha=0.001, learning_rate_init=0.0001, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.0001, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.5s
[CV

/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 1.0min
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=  56.7s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 1.0min
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=  58.6s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.5s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.4s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.4s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   4.2s
[CV] alpha=0.001, lear

/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total=  58.0s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=adam, total= 1.1min
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=adam, total= 1.1min
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=sgd, total=   4.1s
[CV] alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.01, max_iter=250, power_t=0.1, random_state=1337, solver=sgd, total=   4.0s
[CV] alpha=0

/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 2.0min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 2.1min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   7.1s
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   6.9s
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   7.3s
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 2.2min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   6.3s
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=sgd, total=   7.4s
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 2.2min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam 


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=50, power_t=0.1, random_state=1337, solver=adam, total= 2.0min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam, total= 2.3min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam, total= 2.9min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=adam, total= 2.9min
[CV] alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=sgd 
[CV]  alpha=0.001, learning_rate_init=0.1, max_iter=250, power_t=0.1, random_state=1337, solver=sgd, total=  10.4s
[CV] alpha=0.001, le

[Parallel(n_jobs=4)]: Done 120 out of 120 | elapsed: 19.4min finished
/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv=sklearn.cross_validation.StratifiedKFold(labels=[0 1 ..., 3 0], n_folds=5, shuffle=True, random_state=None),
       error_score='raise',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False),
       fit_params=None, iid=True, n_jobs=4,
       param_grid={'solver': ['adam', 'sgd'], 'max_iter': [50, 250, 500], 'learning_rate_init': [0.001, 0.0001, 0.01, 0.1], 'alpha': [0.001], 'power_t': [0.1], 'random_state': [1337]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_log_loss', verbose=2)

In [8]:
print(clf.best_score_)
print(clf.best_params_)

# -2.19642899615
# {'alpha': 0.001, 'max_iter': 50, 'power_t': 0.1, 'random_state': 1337, 'solver': 'sgd'}

# -1.82905221671
# {'alpha': 0.001, 'learning_rate_init': 0.1, 'max_iter': 50, 'power_t': 0.1, 'random_state': 1337, 
#'solver': 'adam'}
# 2.34559 on private LB, 1.91137 on public LB

-1.8296726568
{'alpha': 0.001, 'learning_rate_init': 0.1, 'max_iter': 50, 'power_t': 0.1, 'random_state': 1337, 'solver': 'adam'}


In [9]:
test_preds = clf.predict_proba(df_test)
print(test_preds)

[[ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]
 [ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]
 [ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]
 ..., 
 [ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]
 [ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]
 [ 0.2030242   0.12867658  0.02765295 ...,  0.26141824  0.00517837
   0.01145687]]


In [11]:
test_preds = test_preds.clip(min=0.05, max=0.95) # hack for kaggle since kaggle punishes severly if you predict 
# 1 and it is 0

submission = pd.DataFrame(test_preds, columns=['class'+str(c+1) for c in range(9)])
submission['ID'] = pid
submission.to_csv('../submissions/sub_xgb_stage2_mlp.csv', index=False)
# scores 2.34559 on stage2 private LB and 1.91137 on stage2 public LB

In [12]:
save_classifier('../cache/stage2_mlp_clf.pkl', clf)

In [6]:
x1 = np.load('../cache/train_stage2_x1.npy')
x2 = np.load('../cache/train_stage2_x2.npy')
y1 = np.load('../cache/train_stage2_y1.npy')
y2 = np.load('../cache/train_stage2_y2.npy')

# w1 = np.array([wts_per_class[j] for j in y1], )
# w2 = np.array([wts_per_class[j] for j in y2], )

w1 = np.load('../cache/stage2_train_weights_per_class.npy').tolist()
w2 = np.load('../cache/stage2_train_weights_per_class.npy').tolist()

w1_p = np.array([w1[j] for j in y1], )
w2_p = np.array([w2[j] for j in y2], )

In [7]:
best_params_ = {'alpha': 0.001, 'learning_rate_init': 0.1, 'max_iter': 50, 'power_t': 0.1, 
                'random_state': 1337, 'solver': 'adam'}
# clf1 = MLPClassifier(**clf.best_params_)

clf1 = MLPClassifier(**best_params_)

In [8]:
y1 = y1-1
y2 = y2-1

In [9]:
clf1.fit(x1, y1)

/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.1, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.1, random_state=1337,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [10]:
test_preds = clf1.predict_proba(x2)

In [11]:
test_preds = test_preds.clip(min=0.05, max=0.95)

In [12]:
score2 = log_loss(y2, test_preds, labels = list(range(9)))
print('CV multi_log_loss: {}'.format(score2))

fscore = f1_score(y2, test_preds.argmax(axis=1), labels = list(range(9)), average='weighted')
print('CV f1_score: {}'.format(fscore))

acc = accuracy_score(y2, test_preds.argmax(axis=1))
print('CV accuracy: {}'.format(acc))

print(confusion_matrix(y2, test_preds.argmax(axis=1), labels = list(range(9))))


CV multi_log_loss: 1.884022720626415
CV f1_score: 0.12713710909501086
CV accuracy: 0.2859078590785908
[[  0   0   0   0   0   0 133   0   0]
 [  0   0   0   0   0   0 100   0   0]
 [  0   0   0   0   0   0  19   0   0]
 [  0   0   0   0   0   0 150   0   0]
 [  0   0   0   0   0   0  53   0   0]
 [  0   0   0   0   0   0  59   0   0]
 [  0   0   0   0   0   0 211   0   0]
 [  0   0   0   0   0   0   4   0   0]
 [  0   0   0   0   0   0   9   0   0]]


/home/watts/anaconda2/envs/aind-dog/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
# score with stratified split
# CV multi_log_loss: 1.884022720626415
# CV f1_score: 0.12713710909501086
# CV accuracy: 0.2859078590785908
# [[  0   0   0   0   0   0 133   0   0]
#  [  0   0   0   0   0   0 100   0   0]
#  [  0   0   0   0   0   0  19   0   0]
#  [  0   0   0   0   0   0 150   0   0]
#  [  0   0   0   0   0   0  53   0   0]
#  [  0   0   0   0   0   0  59   0   0]
#  [  0   0   0   0   0   0 211   0   0]
#  [  0   0   0   0   0   0   4   0   0]
#  [  0   0   0   0   0   0   9   0   0]]

# score before stratified split
# CV multi_log_loss: 1.880231068515299
# CV f1_score: 0.13801922169378109
# CV accuracy: 0.2994579945799458
# [[  0   0   0   0   0   0 129   0   0]
#  [  0   0   0   0   0   0 106   0   0]
#  [  0   0   0   0   0   0  24   0   0]
#  [  0   0   0   0   0   0 141   0   0]
#  [  0   0   0   0   0   0  54   0   0]
#  [  0   0   0   0   0   0  55   0   0]
#  [  0   0   0   0   0   0 221   0   0]
#  [  0   0   0   0   0   0   2   0   0]
#  [  0   0   0   0   0   0   6   0   0]]
